// Vocabulary data structure
// Based on Kontext textbook chapter vocabulary (Kapitelwortschatz)
// Source: Klett International - Kontext B1+ / B2

const vocabulary = {
    chapters: [
        {
            id: 1,
            name: "Kapitel 1 - Ankommen",
            words: [
                { de: "ankommen", fr: "arriver", hint: "verbe" },
                { de: "die Ankunft", fr: "l'arrivée", hint: "nom féminin" },
                { de: "der Aufenthalt", fr: "le séjour", hint: "nom masculin" },
                { de: "sich anmelden", fr: "s'inscrire", hint: "verbe réfléchi" },
                { de: "die Unterkunft", fr: "l'hébergement", hint: "nom féminin" },
                { de: "der Mietvertrag", fr: "le contrat de location", hint: "nom masculin" },
                { de: "einziehen", fr: "emménager", hint: "verbe séparable" },
                { de: "ausziehen", fr: "déménager", hint: "verbe séparable" },
                { de: "die Wohngemeinschaft", fr: "la colocation", hint: "nom féminin" },
                { de: "der Mitbewohner", fr: "le colocataire", hint: "nom masculin" },
                { de: "die Kaution", fr: "la caution", hint: "nom féminin" },
                { de: "die Nebenkosten", fr: "les charges", hint: "nom pluriel" },
                { de: "möbliert", fr: "meublé", hint: "adjectif" },
                { de: "geräumig", fr: "spacieux", hint: "adjectif" },
                { de: "gemütlich", fr: "confortable", hint: "adjectif" },
                { de: "die Einrichtung", fr: "l'aménagement", hint: "nom féminin" },
                { de: "sich einleben", fr: "s'acclimater", hint: "verbe réfléchi" },
                { de: "die Nachbarschaft", fr: "le voisinage", hint: "nom féminin" },
                { de: "der Vermieter", fr: "le propriétaire", hint: "nom masculin" },
                { de: "kündigen", fr: "résilier", hint: "verbe" }
            ]
        },
        {
            id: 2,
            name: "Kapitel 2 - Arbeit und Beruf",
            words: [
                { de: "die Bewerbung", fr: "la candidature", hint: "nom féminin" },
                { de: "der Lebenslauf", fr: "le CV", hint: "nom masculin" },
                { de: "das Vorstellungsgespräch", fr: "l'entretien d'embauche", hint: "nom neutre" },
                { de: "sich bewerben", fr: "postuler", hint: "verbe réfléchi" },
                { de: "einstellen", fr: "embaucher", hint: "verbe séparable" },
                { de: "entlassen", fr: "licencier", hint: "verbe" },
                { de: "der Arbeitsvertrag", fr: "le contrat de travail", hint: "nom masculin" },
                { de: "das Gehalt", fr: "le salaire", hint: "nom neutre" },
                { de: "die Überstunden", fr: "les heures supplémentaires", hint: "nom pluriel" },
                { de: "der Urlaub", fr: "les vacances", hint: "nom masculin" },
                { de: "die Teilzeitarbeit", fr: "le travail à temps partiel", hint: "nom féminin" },
                { de: "die Vollzeitstelle", fr: "le poste à temps plein", hint: "nom féminin" },
                { de: "selbstständig", fr: "indépendant", hint: "adjectif" },
                { de: "der Arbeitgeber", fr: "l'employeur", hint: "nom masculin" },
                { de: "der Arbeitnehmer", fr: "l'employé", hint: "nom masculin" },
                { de: "die Qualifikation", fr: "la qualification", hint: "nom féminin" },
                { de: "die Berufserfahrung", fr: "l'expérience professionnelle", hint: "nom féminin" },
                { de: "die Weiterbildung", fr: "la formation continue", hint: "nom féminin" },
                { de: "befördern", fr: "promouvoir", hint: "verbe" },
                { de: "kündigen", fr: "démissionner", hint: "verbe" }
            ]
        },
        {
            id: 3,
            name: "Kapitel 3 - Bildung und Lernen",
            words: [
                { de: "die Ausbildung", fr: "la formation", hint: "nom féminin" },
                { de: "das Studium", fr: "les études", hint: "nom neutre" },
                { de: "die Hochschule", fr: "l'université", hint: "nom féminin" },
                { de: "der Abschluss", fr: "le diplôme", hint: "nom masculin" },
                { de: "die Prüfung", fr: "l'examen", hint: "nom féminin" },
                { de: "bestehen", fr: "réussir", hint: "verbe" },
                { de: "durchfallen", fr: "échouer", hint: "verbe séparable" },
                { de: "die Vorlesung", fr: "le cours magistral", hint: "nom féminin" },
                { de: "das Seminar", fr: "le séminaire", hint: "nom neutre" },
                { de: "die Hausarbeit", fr: "le devoir", hint: "nom féminin" },
                { de: "der Dozent", fr: "le professeur", hint: "nom masculin" },
                { de: "sich einschreiben", fr: "s'inscrire", hint: "verbe réfléchi" },
                { de: "das Stipendium", fr: "la bourse", hint: "nom neutre" },
                { de: "die Bibliothek", fr: "la bibliothèque", hint: "nom féminin" },
                { de: "der Stundenplan", fr: "l'emploi du temps", hint: "nom masculin" },
                { de: "das Semester", fr: "le semestre", hint: "nom neutre" },
                { de: "die Klausur", fr: "le partiel", hint: "nom féminin" },
                { de: "das Referat", fr: "l'exposé", hint: "nom neutre" },
                { de: "forschen", fr: "faire de la recherche", hint: "verbe" },
                { de: "promovieren", fr: "faire un doctorat", hint: "verbe" }
            ]
        },
        {
            id: 4,
            name: "Kapitel 4 - Gesellschaft und Politik",
            words: [
                { de: "die Demokratie", fr: "la démocratie", hint: "nom féminin" },
                { de: "die Wahl", fr: "l'élection", hint: "nom féminin" },
                { de: "wählen", fr: "voter", hint: "verbe" },
                { de: "die Partei", fr: "le parti", hint: "nom féminin" },
                { de: "der Politiker", fr: "le politicien", hint: "nom masculin" },
                { de: "die Regierung", fr: "le gouvernement", hint: "nom féminin" },
                { de: "das Gesetz", fr: "la loi", hint: "nom neutre" },
                { de: "die Verfassung", fr: "la constitution", hint: "nom féminin" },
                { de: "das Grundrecht", fr: "le droit fondamental", hint: "nom neutre" },
                { de: "die Meinungsfreiheit", fr: "la liberté d'expression", hint: "nom féminin" },
                { de: "demonstrieren", fr: "manifester", hint: "verbe" },
                { de: "der Protest", fr: "la protestation", hint: "nom masculin" },
                { de: "die Bürgerinitiative", fr: "l'initiative citoyenne", hint: "nom féminin" },
                { de: "sich engagieren", fr: "s'engager", hint: "verbe réfléchi" },
                { de: "die Gleichberechtigung", fr: "l'égalité des droits", hint: "nom féminin" },
                { de: "die Integration", fr: "l'intégration", hint: "nom féminin" },
                { de: "die Migration", fr: "la migration", hint: "nom féminin" },
                { de: "das Asyl", fr: "l'asile", hint: "nom neutre" },
                { de: "der Flüchtling", fr: "le réfugié", hint: "nom masculin" },
                { de: "die Staatsbürgerschaft", fr: "la nationalité", hint: "nom féminin" }
            ]
        },
        {
            id: 5,
            name: "Kapitel 5 - Umwelt und Nachhaltigkeit",
            words: [
                { de: "der Klimawandel", fr: "le changement climatique", hint: "nom masculin" },
                { de: "die Umweltverschmutzung", fr: "la pollution", hint: "nom féminin" },
                { de: "der Müll", fr: "les déchets", hint: "nom masculin" },
                { de: "recyceln", fr: "recycler", hint: "verbe" },
                { de: "die Mülltrennung", fr: "le tri des déchets", hint: "nom féminin" },
                { de: "erneuerbar", fr: "renouvelable", hint: "adjectif" },
                { de: "die Solarenergie", fr: "l'énergie solaire", hint: "nom féminin" },
                { de: "die Windenergie", fr: "l'énergie éolienne", hint: "nom féminin" },
                { de: "der CO2-Ausstoß", fr: "les émissions de CO2", hint: "nom masculin" },
                { de: "der Treibhauseffekt", fr: "l'effet de serre", hint: "nom masculin" },
                { de: "nachhaltig", fr: "durable", hint: "adjectif" },
                { de: "umweltfreundlich", fr: "écologique", hint: "adjectif" },
                { de: "das Elektroauto", fr: "la voiture électrique", hint: "nom neutre" },
                { de: "der öffentliche Verkehr", fr: "les transports en commun", hint: "nom masculin" },
                { de: "verzichten auf", fr: "renoncer à", hint: "verbe" },
                { de: "sparen", fr: "économiser", hint: "verbe" },
                { de: "die Ressource", fr: "la ressource", hint: "nom féminin" },
                { de: "das Naturschutzgebiet", fr: "la réserve naturelle", hint: "nom neutre" },
                { de: "gefährdet", fr: "menacé", hint: "adjectif" },
                { de: "aussterben", fr: "disparaître", hint: "verbe séparable" }
            ]
        },
        {
            id: 6,
            name: "Kapitel 6 - Medien und Kommunikation",
            words: [
                { de: "die Nachricht", fr: "la nouvelle", hint: "nom féminin" },
                { de: "die Schlagzeile", fr: "le titre", hint: "nom féminin" },
                { de: "berichten", fr: "rapporter", hint: "verbe" },
                { de: "die Quelle", fr: "la source", hint: "nom féminin" },
                { de: "zuverlässig", fr: "fiable", hint: "adjectif" },
                { de: "die Fake News", fr: "les fausses nouvelles", hint: "nom pluriel" },
                { de: "das soziale Netzwerk", fr: "le réseau social", hint: "nom neutre" },
                { de: "der Beitrag", fr: "la publication", hint: "nom masculin" },
                { de: "teilen", fr: "partager", hint: "verbe" },
                { de: "der Follower", fr: "l'abonné", hint: "nom masculin" },
                { de: "der Einfluss", fr: "l'influence", hint: "nom masculin" },
                { de: "die Werbung", fr: "la publicité", hint: "nom féminin" },
                { de: "der Datenschutz", fr: "la protection des données", hint: "nom masculin" },
                { de: "die Privatsphäre", fr: "la vie privée", hint: "nom féminin" },
                { de: "herunterladen", fr: "télécharger", hint: "verbe séparable" },
                { de: "hochladen", fr: "mettre en ligne", hint: "verbe séparable" },
                { de: "der Podcast", fr: "le podcast", hint: "nom masculin" },
                { de: "streamen", fr: "diffuser en streaming", hint: "verbe" },
                { de: "die Meinungsbildung", fr: "la formation d'opinion", hint: "nom féminin" },
                { de: "manipulieren", fr: "manipuler", hint: "verbe" }
            ]
        },
        {
            id: 7,
            name: "Kapitel 7 - Gesundheit und Wohlbefinden",
            words: [
                { de: "die Gesundheit", fr: "la santé", hint: "nom féminin" },
                { de: "die Krankheit", fr: "la maladie", hint: "nom féminin" },
                { de: "der Arzt", fr: "le médecin", hint: "nom masculin" },
                { de: "die Behandlung", fr: "le traitement", hint: "nom féminin" },
                { de: "das Medikament", fr: "le médicament", hint: "nom neutre" },
                { de: "das Rezept", fr: "l'ordonnance", hint: "nom neutre" },
                { de: "die Krankenversicherung", fr: "l'assurance maladie", hint: "nom féminin" },
                { de: "der Stress", fr: "le stress", hint: "nom masculin" },
                { de: "sich entspannen", fr: "se détendre", hint: "verbe réfléchi" },
                { de: "die Ernährung", fr: "l'alimentation", hint: "nom féminin" },
                { de: "ausgewogen", fr: "équilibré", hint: "adjectif" },
                { de: "die Bewegung", fr: "le mouvement", hint: "nom féminin" },
                { de: "trainieren", fr: "s'entraîner", hint: "verbe" },
                { de: "der Schlaf", fr: "le sommeil", hint: "nom masculin" },
                { de: "die Vorsorge", fr: "la prévention", hint: "nom féminin" },
                { de: "impfen", fr: "vacciner", hint: "verbe" },
                { de: "die Therapie", fr: "la thérapie", hint: "nom féminin" },
                { de: "psychisch", fr: "psychique", hint: "adjectif" },
                { de: "das Wohlbefinden", fr: "le bien-être", hint: "nom neutre" },
                { de: "achten auf", fr: "faire attention à", hint: "verbe" }
            ]
        },
        {
            id: 8,
            name: "Kapitel 8 - Kultur und Freizeit",
            words: [
                { de: "die Ausstellung", fr: "l'exposition", hint: "nom féminin" },
                { de: "das Museum", fr: "le musée", hint: "nom neutre" },
                { de: "das Theater", fr: "le théâtre", hint: "nom neutre" },
                { de: "die Aufführung", fr: "la représentation", hint: "nom féminin" },
                { de: "das Konzert", fr: "le concert", hint: "nom neutre" },
                { de: "der Künstler", fr: "l'artiste", hint: "nom masculin" },
                { de: "das Kunstwerk", fr: "l'œuvre d'art", hint: "nom neutre" },
                { de: "beeindruckend", fr: "impressionnant", hint: "adjectif" },
                { de: "die Veranstaltung", fr: "l'événement", hint: "nom féminin" },
                { de: "der Eintritt", fr: "l'entrée", hint: "nom masculin" },
                { de: "buchen", fr: "réserver", hint: "verbe" },
                { de: "das Hobby", fr: "le loisir", hint: "nom neutre" },
                { de: "die Freizeit", fr: "le temps libre", hint: "nom féminin" },
                { de: "sich erholen", fr: "se reposer", hint: "verbe réfléchi" },
                { de: "wandern", fr: "randonner", hint: "verbe" },
                { de: "der Verein", fr: "l'association", hint: "nom masculin" },
                { de: "das Mitglied", fr: "le membre", hint: "nom neutre" },
                { de: "der Wettkampf", fr: "la compétition", hint: "nom masculin" },
                { de: "gewinnen", fr: "gagner", hint: "verbe" },
                { de: "verlieren", fr: "perdre", hint: "verbe" }
            ]
        },
        {
            id: 9,
            name: "Kapitel 9 - Reisen und Tourismus",
            words: [
                { de: "die Reise", fr: "le voyage", hint: "nom féminin" },
                { de: "der Flug", fr: "le vol", hint: "nom masculin" },
                { de: "die Unterkunft", fr: "l'hébergement", hint: "nom féminin" },
                { de: "das Hotel", fr: "l'hôtel", hint: "nom neutre" },
                { de: "die Jugendherberge", fr: "l'auberge de jeunesse", hint: "nom féminin" },
                { de: "buchen", fr: "réserver", hint: "verbe" },
                { de: "der Reiseführer", fr: "le guide de voyage", hint: "nom masculin" },
                { de: "die Sehenswürdigkeit", fr: "le site touristique", hint: "nom féminin" },
                { de: "besichtigen", fr: "visiter", hint: "verbe" },
                { de: "der Strand", fr: "la plage", hint: "nom masculin" },
                { de: "das Gebirge", fr: "la montagne", hint: "nom neutre" },
                { de: "die Landschaft", fr: "le paysage", hint: "nom féminin" },
                { de: "malerisch", fr: "pittoresque", hint: "adjectif" },
                { de: "das Abenteuer", fr: "l'aventure", hint: "nom neutre" },
                { de: "der Rucksack", fr: "le sac à dos", hint: "nom masculin" },
                { de: "die Verspätung", fr: "le retard", hint: "nom féminin" },
                { de: "umsteigen", fr: "changer", hint: "verbe séparable" },
                { de: "die Abfahrt", fr: "le départ", hint: "nom féminin" },
                { de: "der Zoll", fr: "la douane", hint: "nom masculin" },
                { de: "das Visum", fr: "le visa", hint: "nom neutre" }
            ]
        },
        {
            id: 10,
            name: "Kapitel 10 - Wirtschaft und Konsum",
            words: [
                { de: "die Wirtschaft", fr: "l'économie", hint: "nom féminin" },
                { de: "das Unternehmen", fr: "l'entreprise", hint: "nom neutre" },
                { de: "der Umsatz", fr: "le chiffre d'affaires", hint: "nom masculin" },
                { de: "der Gewinn", fr: "le bénéfice", hint: "nom masculin" },
                { de: "der Verlust", fr: "la perte", hint: "nom masculin" },
                { de: "investieren", fr: "investir", hint: "verbe" },
                { de: "der Kunde", fr: "le client", hint: "nom masculin" },
                { de: "der Verbraucher", fr: "le consommateur", hint: "nom masculin" },
                { de: "die Werbung", fr: "la publicité", hint: "nom féminin" },
                { de: "der Preis", fr: "le prix", hint: "nom masculin" },
                { de: "günstig", fr: "bon marché", hint: "adjectif" },
                { de: "teuer", fr: "cher", hint: "adjectif" },
                { de: "die Qualität", fr: "la qualité", hint: "nom féminin" },
                { de: "bestellen", fr: "commander", hint: "verbe" },
                { de: "liefern", fr: "livrer", hint: "verbe" },
                { de: "umtauschen", fr: "échanger", hint: "verbe séparable" },
                { de: "die Rechnung", fr: "la facture", hint: "nom féminin" },
                { de: "bar zahlen", fr: "payer en espèces", hint: "expression" },
                { de: "die Kreditkarte", fr: "la carte de crédit", hint: "nom féminin" },
                { de: "das Konto", fr: "le compte", hint: "nom neutre" }
            ]
        },
        {
            id: 11,
            name: "Kapitel 11 - Technologie und Innovation",
            words: [
                { de: "die Technologie", fr: "la technologie", hint: "nom féminin" },
                { de: "die Entwicklung", fr: "le développement", hint: "nom féminin" },
                { de: "erfinden", fr: "inventer", hint: "verbe" },
                { de: "die Erfindung", fr: "l'invention", hint: "nom féminin" },
                { de: "die künstliche Intelligenz", fr: "l'intelligence artificielle", hint: "nom féminin" },
                { de: "der Roboter", fr: "le robot", hint: "nom masculin" },
                { de: "automatisieren", fr: "automatiser", hint: "verbe" },
                { de: "digitalisieren", fr: "numériser", hint: "verbe" },
                { de: "die Software", fr: "le logiciel", hint: "nom féminin" },
                { de: "die App", fr: "l'application", hint: "nom féminin" },
                { de: "der Algorithmus", fr: "l'algorithme", hint: "nom masculin" },
                { de: "die Daten", fr: "les données", hint: "nom pluriel" },
                { de: "speichern", fr: "sauvegarder", hint: "verbe" },
                { de: "das Passwort", fr: "le mot de passe", hint: "nom neutre" },
                { de: "hacken", fr: "pirater", hint: "verbe" },
                { de: "die Cybersicherheit", fr: "la cybersécurité", hint: "nom féminin" },
                { de: "das Smartphone", fr: "le smartphone", hint: "nom neutre" },
                { de: "vernetzt", fr: "connecté", hint: "adjectif" },
                { de: "die Zukunft", fr: "l'avenir", hint: "nom féminin" },
                { de: "fortschrittlich", fr: "progressiste", hint: "adjectif" }
            ]
        },
        {
            id: 12,
            name: "Kapitel 12 - Beziehungen und Gefühle",
            words: [
                { de: "die Beziehung", fr: "la relation", hint: "nom féminin" },
                { de: "die Freundschaft", fr: "l'amitié", hint: "nom féminin" },
                { de: "die Liebe", fr: "l'amour", hint: "nom féminin" },
                { de: "vertrauen", fr: "faire confiance", hint: "verbe" },
                { de: "das Vertrauen", fr: "la confiance", hint: "nom neutre" },
                { de: "sich verlieben", fr: "tomber amoureux", hint: "verbe réfléchi" },
                { de: "heiraten", fr: "se marier", hint: "verbe" },
                { de: "sich scheiden lassen", fr: "divorcer", hint: "verbe réfléchi" },
                { de: "die Ehe", fr: "le mariage", hint: "nom féminin" },
                { de: "der Partner", fr: "le partenaire", hint: "nom masculin" },
                { de: "streiten", fr: "se disputer", hint: "verbe" },
                { de: "sich versöhnen", fr: "se réconcilier", hint: "verbe réfléchi" },
                { de: "enttäuscht", fr: "déçu", hint: "adjectif" },
                { de: "eifersüchtig", fr: "jaloux", hint: "adjectif" },
                { de: "glücklich", fr: "heureux", hint: "adjectif" },
                { de: "traurig", fr: "triste", hint: "adjectif" },
                { de: "wütend", fr: "en colère", hint: "adjectif" },
                { de: "ängstlich", fr: "anxieux", hint: "adjectif" },
                { de: "sich freuen", fr: "se réjouir", hint: "verbe réfléchi" },
                { de: "vermissen", fr: "manquer", hint: "verbe" }
            ]
        }
    ]
};

// Export for use in quiz.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = vocabulary;
}
